version: '2'
services:  

    rad1:
        image: emane20
        tty: true
        privileged: true
        command: emane -r -l 0 test-radio/platform1.xml
        networks:
            - app1
            - ota-net

    app1:
        image: emane20
        tty: true
        privileged: true
        networks:
            - app1

    rad2:
        image: emane20
        tty: true
        privileged: true
        command: emane -r -l 0 test-radio/platform2.xml
        networks:
            - app2
            - ota-net

    app2:
        image: emane20
        tty: true
        privileged: true
        networks:
            - app2

networks:
    ota-net:
    app1:
    app2: